source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CMPlayerViewController_Example', :exclusive => true do
  pod 'CMPlayerViewController', :path => '../'
end

target 'CMPlayerViewController_Tests', :exclusive => true do
  pod 'CMPlayerViewController', :path => '../'

  
end
